### ISSUE TITLE
Combination of several topics

### ISSUE THREAD

**Issue by OpusK** [eProsima/micro-RTPS-gen#2]
Hi, 

When microRTPSgen can not generate multiple IDL files at the same time (#1), I have tried the following solutions.

For example, use Gen to generate each of "std_msgs::String" and "std_msgs::Bool", and create a topic called "Combination".

Then, in the serialize and deserialize functions of Combination as below, we try to call each of String, Bool topic serialize and deserialize functions. (like rosserial)

```cpp
#include "std_msgs/Bool.hpp"
#include "std_msgs/String.hpp"

namespace test_msgs {

class Combination : public ros2::Topic<Combination>
{
public:
  std_msgs::String message;
  std_msgs::Bool   value;

  Combination():
    Topic("Combination", TEST_MSGS_COMBINATION_TOPIC),
    message(),
    value()
  { 
  };

  virtual bool serialize(MicroBuffer* writer, const Combination* topic)
  {
      uint8_t result;

      message.serialize(writer, &topic->message);
      result = writer->error;
      value.serialize(writer, &topic->value);
      result |= writer->error;
      return result == BUFFER_OK;
  }

  virtual bool deserialize(MicroBuffer* reader, Combination* topic)
  {
      uint8_t result;

      message.deserialize(reader, &topic->message);
      result = reader->error;
      value.deserialize(reader, &topic->value);
      result |= reader->error;
      return result == BUFFER_OK;
  }

  virtual uint32_t size_of_topic(const Combination* topic)
  {
    uint32_t size = 0;

    size += message.size_of_topic(&topic->message);
    size += value.size_of_topic(&topic->value);
    
    return size;
  }


private:

};

} // namespace test_msgs
```

This works well.
Anyway, my question is: Is it ok to use serialization of multiple topics in the above way?

**Comment by lemunozm** [comment]
Hi @OpusK, this combined serialization could generate a problem with the serialization aligment (CDR protocol is used). The new version changes the size_of_topic function to accept the current size of the message, so the size_of_topic method purpose should be like follows:
```c
virtual uint32_t size_of_topic(const Combination* topic)
  {
    uint32_t size = 0;

    size += message.size_of_topic(&topic->message, 0);
    size += value.size_of_topic(&topic->value, size);
    
    return size;
  }
```

Anyway, the feature related to #1 is now available and manage this automatically.

**Comment by OpusK** [comment]
Hi, @lemunozm 

The code I posted was from the beta version.
I come to beta2 and use it like you say.

This is related to #1, so I will close this issue.
Thank you for answer.
