### ISSUE TITLE
Failing micro-RTPS-gen build 

### ISSUE THREAD

**Issue by sivantsiv** [eProsima/micro-RTPS-gen#3]
Hello,

I try to build micro-RTPS-gen project as it is described in the documentation.
I execute **gradle build** command and I receive following errors from IDL Parser module:

_:buildIDLParser FAILED
FAILURE: Build failed with an exception.
* Where:
Build file '/home/slavik/micro-RTPS-gen/thirdparty/IDL-Parser/idl.gradle' line: 18
* What went wrong:
Error resolving plugin [id: 'me.champeau.gradle.antlr4', version: '0.1']
> Could not GET 'https://plugins.gradle.org/api/gradle/3.4.1/plugin/use/me.champeau.gradle.antlr4/0.1'.
   > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty_

Do you know what might be causing this issue?
How can I resolve those problems?
Thank you.

**Comment by richiware** [comment]
It seems something related to Java and SSL certificates. Still I've checked in my machine and it is working. Can you 
check it in another machine?

↪ 2018-07-12 jue 15:46, Slavik Ivantsiv <notifications@github.com>:

**Comment by sivantsiv** [comment]
Hi Ricardo,

Thanks a lot for your help!
I run it on a virtual machine - VirtualBox v.5.2.14 and Ubuntu 18.04.
I tried to do the same on newly generated virtual machine, but I have exactly the same errors.
It could be that Micro-RTPS Gen is not tested on Ubuntu 18.04, or I need to configure special settings of my virtual machine to make it work.
Is there anything else that I can try?
Please let me know if you have any ideas.

Regards,
Slavik

**Comment by sivantsiv** [comment]
Hi Ricardo,

Thanks.
I use the following software:
OpenJDK version 10.0.1;
Gradle version 3.4.1.
I hope it helps.

Regards,
Slavik

**Comment by richiware** [comment]
We are using same versions. Have you upgraded your Ubuntu recently? If not, can you do it? I've also updated master 
branch of micrortpsgen.
↪ 2018-07-17 mar 11:48, Slavik Ivantsiv <notifications@github.com>:

**Comment by sivantsiv** [comment]
Hi Ricardo,

Yes, I updated both Ubuntu and micro-RTPS-gen recently - the same results.
Somebody has similar issues with Gradle as me:
https://github.com/gradle/gradle/issues/3326
I just wonder why you, or somebody else cannot reproduce it.
All other micro-RTPS projects work fine for me!

Regards,
Slavik
